# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_warehouse_bank_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="email",
            field=models.EmailField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="seller_image",
            field=models.ImageField(
                blank=True,
                help_text="16:9 horizontal banner for printed invoice seller block.",
                null=True,
                upload_to="warehouse_seller/",
            ),
        ),
    ]
