# Generated by Django 4.2.30 on 2026-05-13 12:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_phase1a_tyre_pos"),
        ("sales", "0008_supplier_barcode_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional linked customer record (POS / CRM)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="due_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Opening balance owed after checkout (mirrors initial credit_balance when on account)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Non-CREDIT payments received at checkout (counter money)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[("UNPAID", "Unpaid"), ("PARTIAL", "Partially paid"), ("PAID", "Paid")],
                default="PAID",
                help_text="Cash vs credit settlement snapshot at checkout (updated on collections)",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="cgst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="CGST component (intra-state split of gst_amount)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="purchase_price_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Unit cost (from pricing) at sale time for margin reporting",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="sgst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="SGST component (intra-state; sgst = gst_amount - cgst_amount)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
